"""empty message

Revision ID: ed8c61c84c34
Revises: 9c00f0120c37
Create Date: 2021-10-05 11:39:50.454978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed8c61c84c34'
down_revision = '9c00f0120c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'img_url')
    op.add_column('restaurants', sa.Column('img_url', sa.String(length=200), nullable=True))
    op.add_column('total_rating', sa.Column('siksin', sa.Float(), nullable=True))
    op.drop_column('total_rating', 'sikshin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('total_rating', sa.Column('sikshin', mysql.FLOAT(), nullable=True))
    op.drop_column('total_rating', 'siksin')
    op.drop_column('restaurants', 'img_url')
    op.add_column('menus', sa.Column('img_url', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
